Fix right frozen group header position
olifolkerd/tabulator pull request #4270
Opened 2023-08-14 08:28 UTC by ajaborsk

This PR intends to fix the issue #4269 I created yesterday. I simply reproduced the method used for left frozen groups to right frozen groups. Works for me. A little more testing may be necessary, thought there is few risk.

Alexandre

PS : The base code is very clean and clear. Congrats !

2026-01-20 08:55 UTC, azmy60 commented
Hey @ajaborsk ! Sorry for the late reply, I'll be testing this in a minute. One question: it looks like the issue only happens if the column group is on the right?

2026-01-20 10:03 UTC, azmy60 requested changes
Good catch! Looks good to me even though the header line looks slightly shifted (see image below), but that could be fixed in a different PR.

<img width="142" height="111" alt="Image" src="https://github.com/user-attachments/assets/cbf0ee20-8d0d-423c-b05a-99da5c910e17" />

Also, I noticed that the `leftColumns` and `rightColumns` code are super identical. To avoid future mistakes, would you be able to merge them into a single function? At the end, it'd probably look like this:

```js
layoutColumnPosition(allCells) {
  this.layoutFrozenColumns(allCells, this.leftColumns);
  this.layoutFrozenColumns(allCells, this.rightColumns);
}

private layoutFrozenColumns(allCells, columns) {
  // ...
}
```

If all good, will be merging this soon :)

2026-06-18 20:38 UTC, rathboma commented
@azmy60 either take this over of close it plz

2026-06-29 07:54 UTC, azmy60 commented
I'll close this since there's no update. Feel free to reopen if feedback is addressed.

2026-06-29 07:54 UTC, closed without merging