Prevent Recursive Redrawing in AdjustTableSize
olifolkerd/tabulator pull request #4598
Opened 2024-10-12 15:03 UTC by schwarmco

Fixes 4467

2024-10-18 13:55 UTC, kunaljaykam requested changes
You shouldn't make changes in `dist` folder. You can read the contibuting guidelines here: https://tabulator.info/community/pr

![image](https://github.com/user-attachments/assets/d6e4e535-9f1c-4e90-8251-f81364947e23)

2024-10-18 14:23 UTC, schwarmco commented
Reverted the Build Step - Reset dist Folder to origin/master

2024-11-01 11:19 UTC, schwarmco commented
Hi @olifolkerd - any chance this gets merged into a 6.3.1 release soon?

2025-02-04 17:20 UTC, BartNSTCL commented
Still waiting for this PR to be merged in 6.3.0. Not sure if it was forgotten or what was the issue.

2025-04-14 19:04 UTC, rathboma commented
I think this looks fine. Going to merge.

Thanks so much for the contribution! @azmy60 and I are online more than Oli -- we work on [Beekeeper Studio](/beekeeper-studio/beekeeper-studio), and we're helping out on Tabulator because Beekeeper also uses Tabulator, so we want it to be super awesome. :-). So if you need someone, ping us

2025-04-14 19:04 UTC, merged

2025-04-15 12:34 UTC, BartNSTCL commented
When do you expect a release of this version and will it be 6.3.1? Or has it been released as 6.3.1? Just noticed the date last released was Jan 19. I'm interested in the fix for #4467 which looks like it was included.

2025-04-15 14:37 UTC, rathboma commented
I'll probably put out a release by the end of the month. Want to circle back with Oli before I do (and currently in the throws of a Beekeeper release).

2025-05-20 02:30 UTC, Jojoshua commented
@rathboma could this be possibly similar? https://github.com/olifolkerd/tabulator/issues/4142

2025-09-24 10:30 UTC, SimonCVenex commented
> I'll probably put out a release by the end of the month. Want to circle back with Oli before I do (and currently in the throws of a Beekeeper release).

I'm on Tabulator 6.3.1 (current latest version, released in January 2025).

I'm being hit by the stack size bug that is fixed in this PR. You ( @rathboma ) mentioned above you were hoping to put out a release soon with the fix in it, but it doesn't seem to have happened. Any update on this? I'd prefer to use an official release if it's coming, but the bug is a show-stopper so if there's no release planned, I may have to patch it manually at my end.

Thank you for your work on this library. It's fantastic!  😄