default range selection initialization can be disabled
olifolkerd/tabulator pull request #4659
Opened 2024-12-23 20:46 UTC by stefanhoelzl

fixes https://github.com/olifolkerd/tabulator/issues/4634

by default cell [0,0] is selected, when range selection is disabled. With this change this can be disabled, so that on table init no range is selected.

2025-02-02 11:53 UTC, azmy60 commented
Thanks for making a PR! Question - what happens if we press keyboard to navigate while the range does not exist?

2025-02-22 08:06 UTC, stefanhoelzl commented
> Thanks for making a PR! Question - what happens if we press keyboard to navigate while the range does not exist?

when the range does not exist, keyboard presses to navigate do nothing. You first need to select a range before you can navigate by keyboard.

2025-02-28 15:39 UTC, azmy60 requested changes
It's a great idea! But there are some changes needed before merge. I would prefer not to pass boolean flags to function like this if we can avoid that.

2025-02-28 15:39 UTC, azmy60 commented on src/js/modules/SelectRange/SelectRange.js
> +	resetRanges(forceNewRange = true) {
I'm not sure If I like adding a `forceNewRange` flag like this. This could be a sign that we probably need to make a new function. Is it possible to remove this?

2025-02-28 15:39 UTC, azmy60 commented on src/js/modules/SelectRange/SelectRange.js
> +					}
I think this whole thing could be a new method? We can call it `setInitialRange()` or something similar.

2025-02-28 15:39 UTC, azmy60 commented on src/js/modules/SelectRange/SelectRange.js
> +		if(!this.activeRange) return;
Since this could be `undefined`, could you make sure that other places that use `getActiveCell()` handles `undefined` properly?

2025-02-28 15:39 UTC, azmy60 commented on src/js/modules/SelectRange/SelectRange.js
> +			this.resetRanges(false);
If you can make the new `setInitialRange` method, you don't need to pass this boolean flag.

2025-03-02 16:29 UTC, stefanhoelzl commented on src/js/modules/SelectRange/SelectRange.js
> +		if(!this.activeRange) return;
It is used in only two places. One already checked the return value and to the other one I  added an check.

2025-03-02 16:31 UTC, stefanhoelzl commented on src/js/modules/SelectRange/SelectRange.js
> +					}
I refactored `resetRanges` into `resetRanges` and `setDefaultRange`

2025-03-02 16:32 UTC, stefanhoelzl commented on src/js/modules/SelectRange/SelectRange.js
> +			this.resetRanges(false);
yes, the flag is gone no. (see also other comments)

2025-03-04 08:34 UTC, azmy60 approved these changes

2026-06-10 07:10 UTC, merged